#!/usr/bin/env bash

curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

brew install rcm

env RCRC=$HOME/.dotfiles/rcrc rcup

rcup

brew bundle .config/Brewfile
