# Font preferences
font_family             Consolas Regular
bold_font               Consolas Bold
italic_font             Consolas Italic
bold_italic_font        Consolas Bold Italic
font_size               14.0
disable_ligatures       always

# Special layout adjustment for Consolas
adjust_baseline         -4
adjust_line_height      110%
