# Font preferences
font_family             Greybeard 16px
bold_font               Greybeard 16px Bold
italic_font             Greybeard 16px Italic
font_size               16.0
disable_ligatures       always
