# Font preferences
font_family             Greybeard 18px Medium
bold_font               Greybeard 18px Bold
italic_font             Greybeard 18px Italic
font_size               18.0
disable_ligatures       always
adjust_line_height      110%
