# Font preferences
font_family             Iosevka Term Slab Regular
bold_font               Iosevka Term Slab Bold
italic_font             Iosevka Term Slab Italic
bold_italic_font        Iosevka Term Slab Bold Oblique
font_size               14.0
disable_ligatures       always
