# Font preferences
font_family             Luculent Regular
bold_font               Luculent Bold
italic_font             Luculent Italic
bold_italic_font        Luculent Bold Italic
font_size               14.0
disable_ligatures       always
adjust_line_height      105%
