# Font preferences
font_family             Luxi Mono Regular
bold_font               Luxi Mono Bold
italic_font             Luxi Mono Oblique
font_size               13.0
disable_ligatures       always

# Special layout adjustment for Consolas
adjust_baseline         4
adjust_line_height      110%
