# Font preferences
font_family             PragmataPro Mono Regular
bold_font               PragmataPro Mono Bold
italic_font             PragmataPro Mono Italic
bold_italic_font        PragmataPro Mono Bold Italic
font_size               16.0
disable_ligatures       always
adjust_line_height      105%
