# Font preferences
font_family             scientifica Medium
bold_font               scientifica Bold
italic_font             scientifica Italic
font_size               16.0
disable_ligatures       always
adjust_line_height      110%
