# Font preferences
font_family             Source Code Pro Medium
bold_font               Source Code Pro Bold
italic_font             Source Code Pro Medium Italic
bold_italic_font        Source Code Pro Bold Italic
font_size               14.0
disable_ligatures       always
adjust_line_height      105%
