# Font preferences
font_family             Tamzen Medium
bold_font               Tamzen Bold
italic_font             Greybeard Italic
font_size               18.0
disable_ligatures       always
adjust_line_height      110%
