# Font preferences
font_family             Terminus (TTF) Medium
bold_font               Terminus (TTF) Bold
italic_font             Terminus (TTF) Italic
font_size               16.0
disable_ligatures       always
adjust_line_height      110%
