# Font preferences
font_family             Triplicate A Code Regular
bold_font               Triplicate A Code Bold
italic_font             Triplicate A Code Italic
font_size               14.0
disable_ligatures       always
adjust_line_height      110%
