background #00005F
foreground #bcbcbc

selection_background #c8da1c
selection_foreground #1c1d1f

cursor          #DDDDDD

# black
color0 #000000
color8 #bcbcbc

# red
color1 #870000
color9 #ff87ff

# green
color2 #87ff00
color10 #87ff00

# yellow/orange
color3 #ffaf87
color11 #ffff5f

# blue
color4 #005FD7
color12 #005FD7

# magenta/purple
color5 #5f00af
color13 #8787ff

# cyan
color6 #00d7d7
color14 #87ffff

# white
color7 #808080
color15 #ffffff

# tab bar
active_tab_foreground   #000000
active_tab_background   #00C804
inactive_tab_foreground #d2d4de
inactive_tab_background #5C5C5C
tab_bar_background      #00005f
