# Monotone dark theme for Kitty

selection_background #c8da1c
selection_foreground #1c1d1f

foreground      #D9D7CE
cursor          #FFFFFF
background      #121212

color0 #191e2a
color8 #686868
color1 #ed8274
color9 #f28779
color2  #a6cc70
color10 #bae67e
color3  #fad07b
color11 #ffd580
color4  #6dcbfa
color12 #73d0ff
color5  #cfbafa
color13 #d4bfff
color6  #90e1c6
color14 #95e6cb
color7  #c7c7c7
color15 #ffffff

# tab bar
active_tab_foreground   #161821
active_tab_background   #ABABAB
inactive_tab_foreground #d2d4de
inactive_tab_background #5F5F5F
tab_bar_background      #111111
