# Cursor
cursor                #000000
cursor_text_color     background

# Window border
active_border_color     #d75f00

# Tab
tab_bar_background      #ffffff
active_tab_background   #8A8A8A
active_tab_foreground   #000000
inactive_tab_background #F2F2F2
inactive_tab_foreground #8A8A8A

background #ffffea
foreground #000000
selection_background #D2D7FF
color0 #000000
color8 #eaeaea
color1 #880000
color9 #ffeaea
color2 #005500
color10 #eaffea
color3 #663311
color11 #eeee9e
color4 #004488
color12 #cceeff
color5 #770077
color13 #ffeaff
color6 #007777
color14 #eaffff
color7 #eeeecc
color15 #ffffea
selection_foreground #000000
