# XCode WWDC dark theme for Kitty

selection_background #c8da1c
selection_foreground #1c1d1f

background      #292c36
foreground      #e7e8eb
cursor          #DDDDDD

# black
color0   #494d5c
color8   #7f869e

# red
color1   #bb383a
color9   #bb383a

# green
color2   #94c66e
color10  #94c66e

# yellow
color3   #d28e5d
color11  #d28e5d

# blue
color4   #8884c5
color12  #8884c5

# magenta
color5   #b73999
color13  #b73999

# cyan
color6   #00aba4
color14  #00aba4

# white
color7   #e7e8eb
color15  #e7e8eb

# tab bar
active_tab_foreground   #000000
active_tab_background   #00C804
inactive_tab_foreground #d2d4de
inactive_tab_background #5C5C5C
tab_bar_background      #000000
