# XCode WWDC dark theme for Kitty

selection_background #c8da1c
selection_foreground #1c1d1f

background      #1f1f24
foreground      #ffffff
cursor          #DDDDDD

# black
color0   #43454b
color8   #838991

# red
color1   #ff8a7a
color9   #ff8a7a

# green
color2   #83c9bc
color10  #b1faeb

# yellow
color3   #d9c668
color11  #ffa14f

# blue
color4   #4ec4e6
color12  #6bdfff

# magenta
color5   #ff85b8
color13  #ff85b8

# cyan
color6   #cda1ff
color14  #e5cfff

# white
color7   #ffffff
color15  #ffffff

# tab bar
active_tab_foreground   #1f1f24
active_tab_background   #84A0C6
inactive_tab_foreground #d2d4de
inactive_tab_background #353a50
tab_bar_background      #060607
