# # Installation dependencies and settings
# -----------------------------------------------------------------------------
cask_args appdir: "/Applications"

# Shell
# -----------------------------------------------------------------------------
brew "bash"
brew "fish"

# Programming language managers
# -----------------------------------------------------------------------------
brew "mise"

# Database
# -----------------------------------------------------------------------------
brew "sqlite3"

# CLI Tools or other end-use software
# -----------------------------------------------------------------------------
brew "asciinema"
brew "btop"
brew "bcrypt"
brew "curl"
brew "darkhttpd"
brew "eza"
brew "ffmpeg"
brew "fzy"
brew "git"
brew "groff"
brew "htop"
brew "imagemagick"
brew "ouch"
brew "parallel"
brew "pwgen"
brew "recutils"
brew "redis"
brew "rlwrap"
brew "rsync"
brew "sdcv"
brew "tree"
brew "universal-ctags"
brew "vim"
brew "weechat"
brew "wget"

# Interactive fiction
# -----------------------------------------------------------------------------
brew "frotz"
brew "glulxe"

# Cask applications
# -----------------------------------------------------------------------------
cask "audacity"
cask "docker"
cask "flux"
cask "ghostty"
cask "hammerspoon"
cask "vlc"
