# Allow remote control access from scripts
allow_remote_control    yes
listen_on               unix:/tmp/mykitty

# Scrollback amount
scrollback_lines        10000

# Layout
placement_strategy top-left
window_border_width     4
window_margin_width     0
window_padding_width    0
draw_minimal_borders    no
confirm_os_window_close 1

# Window shortcuts
map shift+left neighboring_window left
map shift+right neighboring_window right
map shift+up neighboring_window up
map shift+down neighboring_window down

# Option as alt
macos_option_as_alt yes

# Tab bar
tab_bar_edge            top
tab_bar_style           fade
tab_fade                1 1 1 1
tab_bar_margin_height   0.0 4.0
active_tab_font_style   bold
inactive_tab_font_style normal

# Tab bar controls. New tab next to current with same working directory.
map super+t new_tab_with_cwd !neighbor
map kitty_mod+enter new_window_with_cwd

# Cursor
shell_integration no-cursor
cursor_shape block
cursor_blink_interval 0

# Font config for development
# include fonts/tamzen.conf

# For prose
# include fonts/triplicate.conf

# For prose writing
# include fonts/triplicate.conf

# Font for MUD & Rogues
# include fonts/cozette.conf

# Font for IF
include fonts/greybeard.conf

# Etc. fonts
# include fonts/source_code_pro.conf
# include fonts/iosevka.conf
# include fonts/go_mono.conf
# include fonts/dina.conf
# include fonts/scientifica.conf
# include fonts/pragmata_pro.conf
# include fonts/hermit.conf
# include fonts/luculent.conf
# include fonts/triplicate.conf
# include fonts/consolas.conf
# include fonts/montecarlo.conf
# include fonts/luxi_mono.conf
# include fonts/terminus.conf

# BEGIN_KITTY_THEME
include current-theme.conf
# END_KITTY_THEME
